name: deploy

on:
  pull_request:
    branches: [ "main", "develop" ]
    types:
      - closed

# 이벤트가 발생시 해당 작업들 실행
jobs:
  # 작업 분류 : 배포 (빌드와 배포를 분류 가능)
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: shell Stop Second Front Health Check
        run: |
          echo "$SSH_PEM_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_KNOWN_HOSTS} '~/script.sh'
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_PEM_KEY: ${{secrets.SSH_PEM_KEY}}
